### ISSUE TITLE
Feature Request - Non-linear execution cell layout

### ISSUE THREAD

**Issue by danilo-bc** [ChifiSource/Olive.jl#13]
I saw this repository via Logan Kilpatrick and his contributions to the Julia community. Since I loved the idea of this novel notebook format, and given that the project is in pre-release, is it possible to think about parallel-like execution blocks?

The idea is that some scientific situations and code are better represented as parallel blocks (like Simulink block diagrams). The blocks themselves don't need to execute strictly in parallel, but at least have some sort of semaphore in which the execution flow only proceeds once all proceeds.

Thank you so much for the hard work :) I'm loving to read about the project.

**Comment by emmettgb** [comment]
Hi -- sorry this is the first I am seeing of this -- been very busy at " actual" work. I think that extensions might be able to facilitate something like this already. This is the exact kind of thing I am creating this for, and I think here in a few weeks you will be happy with the result!
##### way too much detail
The behavior of cells and projects can be completely changed just by writing new functions! So, say for Simulink diagrams, you could program for example an armature cell ... load cell, essentially any cell you want to create you can make and change the behavior of. If you wanted to be less specific, we could simply make a parallel cell extension. Creating two cells in parallel would be as simple as writing a new symbolic build function for it. Here is the default build function for a code cell:
```julia
function build(c::Connection, cm::ComponentModifier, cell::Cell{:code})
    text = replace(cell.source, "\n" => "</br>")
    tm = TextModifier(text)
    ToolipsMarkdown.julia_block!(tm)
    outside = div("cellcontainer$(cell.n)", class = cell)
    inside = ToolipsDefaults.textdiv("cell$(cell.n)", text = string(tm))
    inside[:class] = "input_cell"
     style!(inside, "text-color" => "white !important")
     style!(outside, "transition" => 1seconds)
    number = h("cell", 1, text = "$(cell.n)", class = "cell_number")
    output = divider("cell$(cell.n)" * "out", class = "output_cell", text = cell.outputs)
    push!(outside, number, inside, output)
    outside
end
```
For a bunch more information you really did not ask for (but I think is cool,) the other cells are also willed into existence like this:
```julia
function build(c::Connection, cm::ComponentModifier, cell::Cell{:markdown})
    tlcell = div("cell$(cell.n)", class = "cell")
    innercell = tmd("cell$(cell.n)tmd", cell.source)
    on(c, cm, tlcell, "dblclick") do cm::ComponentModifier
        set_text!(cm, tlcell, replace(cell.source, "\n" => "</br>"))
        cm["olivemain"] = "cell" => string(cell.n)
        cm[tlcell] = "contenteditable" => "true"
    end
    tlcell[:children] = [innercell]
    tlcell
end


function build(c::Connection, cm::ComponentModifier, cell::Cell{:ipynb})
    filecell = div("cell$(cell.n)", class = "cell-ipynb")
    on(c, cm, filecell, "click") do cm::ComponentModifier
        cm["olivemain"] = "cell" => string(cell.n)
    end
    on(c, cm, filecell, "dblclick") do cm::ComponentModifier
        evaluate(c, cell, cm)
    end
    fname = a("$(cell.source)", text = cell.source)
    style!(fname, "color" => "white", "font-size" => 15pt)
    push!(filecell, fname)
    filecell
end
```
The ipynb cell shows why this is cool, because we can build a new cell name based on a filename, e.g. .ipynb and then have a read function to turn it into cells, and we can very easily create a reader for any file that populates throughout the UI. We can also have different files read in different ways, because these all use evaluate functions. Point being we can completely change how this UI works whenever we want to, we could even have it program through a PyCall layer or whatever else we wanted to do. It's also really cool because it uses Revise and modules rather than kernels, so it ends up using a lot less memory!

 Once I actually get the base project done (hopefully really soon, the project is really getting there) I would be happy to work on extensions for specific use-cases, like Simulink -- or make efforts to make an easily customizable version of an extension that makes non-linear execution viable for many different applications.

**Comment by danilo-bc** [comment]
Thank you for the in-depth response, I can see your passion towards the project, although there's little time to it.

**Comment by emmettgb** [comment]
This will be here:
https://github.com/ChifiSource/OliveFlexCells.jl
closing this.
